name: Nodejs CI CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ojiset22
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ojiset22/nusapod-nodejs:latest

      - name: Trigger NusaPod Webhook (Server Pull)
        run: |
          echo "Calling NusaPod Webhook.."
          curl -X POST https://nusapod.com/containers/webhook \
            -H "Content-Type: application/json" \
            -H "X-Webhook-Token: ${{ secrets.WEBHOOK_TOKEN }}" \
            -d '{"name":"nodejs1","image":"ojiset22/nusapod-nodejs:latest"}'